--A10P2

CREATE TABLE PILOT_DIM
(
	PILOT_ID INT NOT NULL IDENTITY,
	EMP_NUM INT,
	EMP_FNAME VARCHAR(15),
	EMP_LNAME VARCHAR(15)
)


ALTER TABLE PILOT_DIM
ADD CONSTRAINT PK_PILOT_DIM PRIMARY KEY(PILOT_ID)

CREATE TABLE AIRCRAFT_DIM
(
	AC_ID INT NOT NULL IDENTITY,
	AC_NUMBER VARCHAR(5),
	MOD_CODE VARCHAR(10)
)

ALTER TABLE AIRCRAFT_DIM
ADD CONSTRAINT PK_AIRCRAFT_DIM PRIMARY KEY(AC_ID)

CREATE TABLE DATE_DIM
(
	DATE_ID INT NOT NULL IDENTITY,
	CHAR_DATE DATETIME
)

ALTER TABLE DATE_DIM
ADD CONSTRAINT PK_DATE_DIM PRIMARY KEY(DATE_ID)


CREATE TABLE FACT
(
	PILOT_ID INT NOT NULL,
	AC_ID INT NOT NULL,
	DATE_ID INT NOT NULL,
	FUEL_USED FLOAT(8),
	DISTANCE FLOAT(8),
	REVENUE FLOAT(8)
)

ALTER TABLE FACT 
ADD CONSTRAINT PK_FACT PRIMARY KEY(PILOT_ID,AC_ID,DATE_ID)

ALTER TABLE FACT 
ADD CONSTRAINT FK_FACT_PILOT_DIM FOREIGN KEY(PILOT_ID)
REFERENCES PILOT_DIM

ALTER TABLE FACT 
ADD CONSTRAINT FK_FACT_AC_DIM FOREIGN KEY(AC_ID)
REFERENCES AIRCRAFT_DIM

ALTER TABLE FACT 
ADD CONSTRAINT FK_FACT_DATE_DIM FOREIGN KEY(DATE_ID)
REFERENCES DATE_DIM


CREATE TABLE STAGING
(
	EMP_NUM INT,
	AC_NUMBER VARCHAR(5),
	MOD_CODE VARCHAR(10),
	CHAR_DATE DATETIME,
	FUEL_USED FLOAT(8),
	DISTANCE FLOAT(8),
	REVENUE FLOAT(8),
	PILOT_ID INT,
	AC_ID INT,
	DATE_ID INT 
)