
CREATE PROCEDURE A10P3

AS
BEGIN

ALTER TABLE FACT 
DROP CONSTRAINT FK_FACT_PILOT_DIM 


ALTER TABLE FACT 
DROP CONSTRAINT FK_FACT_AC_DIM

ALTER TABLE FACT 
DROP CONSTRAINT FK_FACT_DATE_DIM 

TRUNCATE TABLE AIRCRAFT_DIM
TRUNCATE TABLE DATE_DIM
TRUNCATE TABLE PILOT_DIM
TRUNCATE TABLE FACT
TRUNCATE TABLE STAGING


INSERT INTO AIRCRAFT_DIM (AC_NUMBER,MOD_CODE)
(SELECT AC_NUMBER, MOD_CODE
FROM AIRCRAFT)

INSERT INTO DATE_DIM (CHAR_DATE)
	(SELECT DISTINCT CHAR_DATE
	FROM CHARTER)

INSERT INTO PILOT_DIM (EMP_NUM, EMP_FNAME, EMP_LNAME)
	(SELECT P.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME
	FROM PILOT P INNER JOIN EMPLOYEE E ON E.EMP_NUM = P.EMP_NUM)


INSERT INTO STAGING (EMP_NUM, AC_NUMBER, MOD_CODE, CHAR_DATE, FUEL_USED, DISTANCE, REVENUE)
	(SELECT P.EMP_NUM, A.AC_NUMBER, A.MOD_CODE, C.CHAR_DATE, C.CHAR_FUEL_GALLONS, CHAR_DISTANCE, C.char_fuel_gallons * M.mod_chg_mile
	FROM PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM 
		INNER JOIN CREW ON CREW.EMP_NUM = E.EMP_NUM
		INNER JOIN CHARTER C ON C.CHAR_TRIP = CREW.CHAR_TRIP
		INNER JOIN AIRCRAFT A ON C.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE)



UPDATE STAGING
	SET PILOT_ID = (SELECT PILOT_ID
					FROM PILOT_DIM
					WHERE PILOT_DIM.EMP_NUM = STAGING.EMP_NUM)

UPDATE STAGING
	SET DATE_ID = (SELECT DATE_ID
					FROM DATE_DIM
					WHERE STAGING.CHAR_DATE = DATE_DIM.CHAR_DATE)
					
UPDATE STAGING
	SET AC_ID = (SELECT AC_ID
				FROM AIRCRAFT_DIM
				WHERE AIRCRAFT_DIM.AC_NUMBER = STAGING.AC_NUMBER)
					

INSERT INTO FACT (PILOT_ID, AC_ID, DATE_ID, FUEL_USED, DISTANCE, REVENUE)
	SELECT PILOT_ID, AC_ID, DATE_ID, FUEL_USED, DISTANCE, REVENUE
	FROM STAGING


END
GO
